<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FeriaDelAgricultorModels\FeriaDelAgricultorModels.csproj" />
    <ProjectReference Include="..\FeriaDelAgricultorController\FeriaDelAgricultorController.csproj" />
  </ItemGroup>

  <!-- COPIAR AUTOMÁTICAMENTE LOS CSV -->
  <ItemGroup>
    <Content Include="..\..\Data\*.csv">
      <Link>Data\%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
