<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Data\NewFolder\**" />
		<Content Remove="Data\NewFolder\**" />
		<EmbeddedResource Remove="Data\NewFolder\**" />
		<None Remove="Data\NewFolder\**" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\src\FeriaDelAgricultorController\FeriaDelAgricultorController.csproj" />
		<ProjectReference Include="..\src\FeriaDelAgricultorModels\FeriaDelAgricultorModels.csproj" />
	</ItemGroup>

	<!-- Mantiene la carpeta Data visible en el proyecto -->
	<ItemGroup>
		<Folder Include="Data\" />
	</ItemGroup>

	<!-- Copiar TODOS los CSV de Data al output (bin) conservando la carpeta Data -->
	<ItemGroup>
		<Content Include="Data\*.csv">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

</Project>
